version: 2.0

references:
  node11: &node11image
    docker:
      - image: circleci/node:11
  node11browser: &node11browsersimage
    docker:
      - image: circleci/node:11-browsers

  install_npm_default: &install_npm
    run: 
      name: Update npm
      command: 'sudo npm install -g npm@latest'
  restore_cache_default: &restore_cache # special step to restore the dependency cache
    restore_cache:
        # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
        key: dependency-cache-{{ checksum "package.json" }}
  install_npm_packages_default: &install_npm_packages
    run:
        name: Install npm packages
        command: npm install
  save_cache_default: &save_cache # special step to save the dependency cache
    save_cache: 
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules


jobs:
  lint_and_test_node_11: &lint_and_test
    <<: *node11image
    steps: 
      - checkout
      - *install_npm
      - *restore_cache
      - *install_npm_packages
      - *save_cache
      - run: &lint
          name: Lint
          command: npm run lint-check
      - run: &test
          name: Test
          command: npm test


   # Pre-Release Test Integration

  pre_release_test_integration_node_11: &pre_release_test_integration
    <<: *node11browsersimage
    steps: 
      - checkout
      - *install_npm
      - *restore_cache
      - *install_npm_packages
      - *save_cache
      - run:
          name: Build browser tests and bundle
          command: ./integration-test/scripts/build-pre-release-test.sh
      - run:
          name: Test bundles
          command: |
            cd integration-test
            npm run test:pre-release

  # Post-Release Test Integration

  post_release_test_integration_node_11: &post_release_test_integration
    <<: *node11browsersimage
    steps: 
      - checkout
      - *install_npm
      - *restore_cache
      - *install_npm_packages
      - *save_cache
      - run:
          name: Build browser tests
          command: ./integration-test/scripts/build-post-release-test.sh
      - run:
          name: Test unpkg
          command: |
            cd integration-test
            npm run test:post-release

  npm_audit_node_11: &npm_audit
    <<: *node11image
    steps: 
      - checkout
      - *install_npm
      - *restore_cache
      - *install_npm_packages
      - *save_cache
      - run: 
          name: install hub
          command: sudo apt install hub
      - run: &npm_audit_fix
          name: npm audit --fix
          command: npm audit --fix
      # - run: &submit_pr
      #     name: 
      #     command: npm test


            
workflows:
  version: 2
  test_all:
    jobs:
      - lint_and_test_node_11
      - pre_release_test_integration_node_11
  nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - post_release_test_integration_node_11
       - npm_audit_node_11
