version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:11
    steps:
      - run:
          name: Lint
          command: |
            npm run lint
      - run:
          name: Tests
          command: |
            npm run test
